/*
 * BSP_USART.h
 *
 *  Created on: Apr 27, 2023
 *      Author: nayye
 */

#ifndef BSP_USART_H_
#define BSP_USART_H_

#include <main.h>

/*Enable USART and UART clocks*/

#define ENABLE_USART1_CLOCK	rcc->APB2ENR  = (rcc->APB2ENR = 1U<<14 | rcc->APB2ENR)
#define ENABLE_USART2_CLOCK	rcc->APB1ENR1  = (rcc->APB1ENR1 = 1U<<17 | rcc->APB1ENR1)
#define ENABLE_USART3_CLOCK	rcc->APB1ENR1  = (rcc->APB1ENR1 = 1U<<18 | rcc->APB1ENR1)
#define ENABLE_UART4_CLOCK	rcc->APB1ENR1  = (rcc->APB1ENR1 = 1U<<19 | rcc->APB1ENR1)
#define ENABLE_UART5_CLOCK	rcc->APB1ENR1  = (rcc->APB1ENR1 = 1U<<20 | rcc->APB1ENR1)
/*USART and UART registers*/
#define USART1_BASE		(PERIPH_BASE + 0x00013800)	//0x4001 3800
#define USART1		((UART_Typedef*)USART1_BASE)

#define USART2_BASE		(PERIPH_BASE + 0x00004400)	//0x4000 4400
#define USART2		((UART_Typedef*)USART2_BASE)

#define USART3_BASE		(PERIPH_BASE + 0x00004800)	//0x4000 4800
#define USART3		((UART_Typedef*)USART3_BASE)

#define UART4_BASE		(PERIPH_BASE + 0x00004C00)	//0x4000 4C00
#define UART4		((UART_Typedef*)UART4_BASE)

#define UART5_BASE		(PERIPH_BASE + 0x00005000)	//0x4000 5000
#define UART5		((UART_Typedef*)UART5_BASE)

/*USART_CR1*/
/*
typedef struct {

	UART_Typedef *instance;
	uint32_t world_length;
	uint32_t over_sampling;
	uint32_t parity;





}UART_Handle_Typedef


*/



#define USART_CR1_UE_POS		(0U)
#define USART_CR1_UE_MSK		0x1UL << USART_CR1_UE_POS
#define USART_CR1_UE			USART_CR1_UE_MSK

#define USART_CR1_UESM_POS		(1U)
#define USART_CR1_UESM_MSK		0x1UL << USART_CR1_UESM_POS
#define USART_CR1_UESM			USART_CR1_UESM_MSK

#define USART_CR1_RE_POS		(2U)
#define USART_CR1_RE_MSK		0x1UL << USART_CR1_RE_POS
#define USART_CR1_RE			USART_CR1_RE_MSK

#define USART_CR1_TE_POS		(3U)
#define USART_CR1_TE_MSK		0x1UL << USART_CR1_TE_POS
#define USART_CR1_TE			USART_CR1_TE_MSK


#define USART_CR1_IDLEIE_POS	(4U)
#define USART_CR1_IDLEIE_MSK	0x1UL << USART_CR1_IDLEIE_POS
#define USART_CR1_IDLEIE		USART_CR1_IDLEIE_MSK


#define USART_CR1_RXFNEIE_POS	(5U)
#define USART_CR1_RXFNEIE_MSK	0x1UL << USART_CR1_RXFNEIE_POS
#define USART_CR1_RXFNEIE		USART_CR1_RXFNEIE_MSK

#define USART_CR1_TCIE_POS		(6U)
#define USART_CR1_TCIE_MSK		0x1UL << USART_CR1_TCIE_POS
#define USART_CR1_TCIE			USART_CR1_TCIE_MSK

#define USART_CR1_TXFNFIE_POS	(7U)
#define USART_CR1_TXFNFIE_MSK	0x1UL << USART_CR1_TXFNFIE_POS
#define USART_CR1_TXFNFIE		USART_CR1_TXFNFIE_MSK

#define USART_CR1_PEIE_POS		(8U)
#define USART_CR1_PEIE_MSK		0x1UL << USART_CR1_PEIE_POS
#define USART_CR1_PEIE			USART_CR1_PEIE_MSK

#define USART_CR1_PS_POS		(9U)
#define USART_CR1_PS_MSK		0x1UL << USART_CR1_PS_POS
#define USART_CR1_PS			USART_CR1_PS_MSK

#define USART_CR1_PCE_POS		(10U)
#define USART_CR1_PCE_MSK		0x1UL << USART_CR1_PCE_POS
#define USART_CR1_PCE			USART_CR1_PCE_MSK

#define USART_CR1_WAKE_POS		(11U)
#define USART_CR1_WAKE_MSK		0x1UL << USART_CR1_WAKE_POS
#define USART_CR1_WAKE			USART_CR1_WAKE_MSK

#define USART_CR1_M0_POS		(12U)
#define USART_CR1_M0_MSK		0x1UL << USART_CR1_M0_POS
#define USART_CR1_M0			USART_CR1_M0_MSK

#define USART_CR1_MME_POS		(13U)
#define USART_CR1_MME_MSK		0x1UL << USART_CR1_MME_POS
#define USART_CR1_MME			USART_CR1_MME_MSK


#define USART_CR1_CMIE_POS		(14U)
#define USART_CR1_CMIE_MSK		0x1UL << USART_CR1_CMIE_POS
#define USART_CR1_CMIE			USART_CR1_CMIE_MSK

#define USART_CR1_OVER8_POS		(15U)
#define USART_CR1_OVER8_MSK		0x1UL << USART_CR1_OVER8_POS
#define USART_CR1_OVER8			USART_CR1_OVER8_MSK

#define USART_CR1_DEDT_POS		(16U)
#define USART_CR1_DEDT_MSK		0x1UL << USART_CR1_DEDT_POS
#define USART_CR1_DEDT			USART_CR1_DEDT_MSK
#define USART_CR1_DEDT_0		0x1UL << USART_CR1_DEDT_POS
#define USART_CR1_DEDT_1		0x2UL << USART_CR1_DEDT_POS
#define USART_CR1_DEDT_2		0x3UL << USART_CR1_DEDT_POS
#define USART_CR1_DEDT_3		0x4UL << USART_CR1_DEDT_POS
#define USART_CR1_DEDT_4		0x5UL << USART_CR1_DEDT_POS


#define USART_CR1_DEAT_POS		(21U)
#define USART_CR1_DEAT_MSK		0x1UL << USART_CR1_DEAT_POS
#define USART_CR1_DEAT			USART_CR1_DEAT_MSK
#define USART_CR1_DEAT_0		0x1UL << USART_CR1_DEAT_POS
#define USART_CR1_DEAT_1		0x2UL << USART_CR1_DEAT_POS
#define USART_CR1_DEAT_2		0x3UL << USART_CR1_DEAT_POS
#define USART_CR1_DEAT_3		0x4UL << USART_CR1_DEAT_POS
#define USART_CR1_DEAT_4		0x5UL << USART_CR1_DEAT_POS

#define USART_CR1_RTOIE_POS		(26U)
#define USART_CR1_RTOIE_MSK		0x1UL << USART_CR1_RTOIE_POS
#define USART_CR1_RTOIE			USART_CR1_RTOIE_MSK

#define USART_CR1_EOBIE_POS		(27U)
#define USART_CR1_EOBIE_MSK		0x1UL << USART_CR1_EOBIE_POS
#define USART_CR1_EOBIE			USART_CR1_EOBIE_MSK

#define USART_CR1_M1_POS		(28U)
#define USART_CR1_M1_MSK		0x1UL << USART_CR1_M1_POS
#define USART_CR1_M1			USART_CR1_M1_MSK

#define USART_CR1_FIFOEN_POS		(29U)
#define USART_CR1_FIFOEN_MSK		0x1UL << USART_CR1_FIFOEN_POS
#define USART_CR1_FIFOEN			USART_CR1_FIFOEN_MSK

#define USART_CR1_TXFEIE_POS		(30U)
#define USART_CR1_TXFEIE_MSK		0x1UL << USART_CR1_TXFEIE_POS
#define USART_CR1_TXFEIE			USART_CR1_TXFEIE_MSK

#define USART_CR1_RXFFIE_POS		(31U)
#define USART_CR1_RXFFIE_MSK		0x1UL << USART_CR1_RXFFIE_POS
#define USART_CR1_RXFFIE			USART_CR1_RXFFIE_MSK


/*USART_CR2*/
#define USART_CR2_SLVEN_POS		(0U)
#define USART_CR2_SLVEN_MSK		0x1UL << USART_CR2_SLVEN_POS
#define USART_CR2_SLVEN			USART_CR2_SLVEN_MSK

#define USART_CR2_DIS_NSS_POS		(3U)
#define USART_CR2_DIS_NSS_MSK		0x1UL << USART_CR2_DIS_NSS_POS
#define USART_CR2_DIS_NSS			USART_CR2_DIS_NSS_MSK

#define USART_CR2_ADDM7_POS		(4U)
#define USART_CR2_ADDM7_MSK		0x1UL << USART_CR2_ADDM7_POS
#define USART_CR2_ADDM7			USART_CR2_ADDM7_MSK

#define USART_CR2_LBDL_POS		(5U)
#define USART_CR2_LBDL_MSK		0x1UL << USART_CR2_LBDL_POS
#define USART_CR2_LBDL			USART_CR2_LBDL_MSK

#define USART_CR2_LBDIE_POS		(6U)
#define USART_CR2_LBDIE_MSK		0x1UL << USART_CR2_LBDIE_POS
#define USART_CR2_LBDIE			USART_CR2_LBDIE_MSK

#define USART_CR2_LBCL_POS		(8U)
#define USART_CR2_LBCL_MSK		0x1UL << USART_CR2_LBCL_POS
#define USART_CR2_LBCL			USART_CR2_LBCL_MSK

#define USART_CR2_CPHA_POS		(9U)
#define USART_CR2_CPHA_MSK		0x1UL << USART_CR2_CPHA_POS
#define USART_CR2_CPHA			USART_CR2_CPHA_MSK

#define USART_CR2_CPOL_POS		(10U)
#define USART_CR2_CPOL_MSK		0x1UL << USART_CR2_CPOL_POS
#define USART_CR2_CPOL			USART_CR2_CPOL_MSK


#define USART_CR2_CLKEN_POS		(11U)
#define USART_CR2_CLKEN_MSK		0x1UL << USART_CR2_CLKEN_POS
#define USART_CR2_CLKEN			USART_CR2_CLKEN_MSK

#define USART_CR2_STOP_POS		(12U)
#define USART_CR2_STOP_MSK		0x1UL << USART_CR2_STOP_POS
#define USART_CR2_STOP			USART_CR2_STOP_MSK
#define USART_CR2_STOP_0		0x1UL << USART_CR2_STOP_POS
#define USART_CR2_STOP_1		0x2UL << USART_CR2_STOP_POS

#define USART_CR2_LINEN_POS		(14U)
#define USART_CR2_LINEN_MSK		0x1UL << USART_CR2_LINEN_POS
#define USART_CR2_LINEN			USART_CR2_LINEN_MSK

#define USART_CR2_SWAP_POS		(15U)
#define USART_CR2_SWAP_MSK		0x1UL << USART_CR2_SWAP_POS
#define USART_CR2_SWAP			USART_CR2_SWAP_MSK

#define USART_CR2_RXINV_POS		(16U)
#define USART_CR2_RXINV_MSK		0x1UL << USART_CR2_RXINV_POS
#define USART_CR2_RXINV			USART_CR2_RXINV_MSK

#define USART_CR2_TXINV_POS		(17U)
#define USART_CR2_TXINV_MSK		0x1UL << USART_CR2_TXINV_POS
#define USART_CR2_TXINV			USART_CR2_TXINV_MSK

#define USART_CR2_DATAINV_POS		(18U)
#define USART_CR2_DATAINV_MSK		0x1UL << USART_CR2_DATAINV_POS
#define USART_CR2_DATAINV			USART_CR2_DATAINV_MSK

#define USART_CR2_MSBFIRST_POS		(19U)
#define USART_CR2_MSBFIRST_MSK		0x1UL << USART_CR2_MSBFIRST_POS
#define USART_CR2_MSBFIRST			USART_CR2_MSBFIRST_MSK

#define USART_CR2_ABREN_POS		(20U)
#define USART_CR2_ABREN_MSK		0x1UL << USART_CR2_ABREN_POS
#define USART_CR2_ABREN			USART_CR2_ABREN_MSK

#define USART_CR2_ABRMOD_POS		(21U)
#define USART_CR2_ABRMOD_MSK		0x3UL << USART_CR2_ABRMOD_POS
#define USART_CR2_ABRMOD			USART_CR2_ABRMOD_MSK
#define USART_CR2_ABRMOD_0			0x1UL << USART_CR2_ABRMOD_POS
#define USART_CR2_ABRMOD_1			0x2UL << USART_CR2_ABRMOD_POS

#define USART_CR2_RTOEN_POS		(23U)
#define USART_CR2_RTOEN_MSK		0x1UL << USART_CR2_RTOEN_POS
#define USART_CR2_RTOEN			USART_CR2_RTOEN_MSK

#define USART_CR2_ADD_POS		(24U)
#define USART_CR2_ADD_MSK		0xFFUL << USART_CR2_ADD_POS
#define USART_CR2_ADD			USART_CR2_ADD_MSK

/*USART_CR3*/

#define USART_CR2_EIE_POS		(0U)
#define USART_CR2_EIE_MSK		0x1UL << USART_CR2_EIE_POS
#define USART_CR2_EIE			USART_CR2_EIE_MSK

#define USART_CR2_IREN_POS		(1U)
#define USART_CR2_IREN_MSK		0x1UL << USART_CR2_IREN_POS
#define USART_CR2_IREN			USART_CR2_IREN_MSK

#define USART_CR2_IRLP_POS		(2U)
#define USART_CR2_IRLP_MSK		0x1UL << USART_CR2_IRLP_POS
#define USART_CR2_IRLP			USART_CR2_IRLP_MSK

#define USART_CR2_HDSEL_POS		(3U)
#define USART_CR2_HDSEL_MSK		0x1UL << USART_CR2_HDSEL_POS
#define USART_CR2_HDSEL			USART_CR2_HDSEL_MSK

#define USART_CR2_NACK_POS		(4U)
#define USART_CR2_NACK_MSK		0x1UL << USART_CR2_NACK_POS
#define USART_CR2_NACK			USART_CR2_NACK_MSK

#define USART_CR2_SCEN_POS		(5U)
#define USART_CR2_SCEN_MSK		0x1UL << USART_CR2_SCEN_POS
#define USART_CR2_SCEN			USART_CR2_SCEN_MSK

#define USART_CR2_DMAR_POS		(6U)
#define USART_CR2_DMAR_MSK		0x1UL << USART_CR2_DMAR_POS
#define USART_CR2_DMAR			USART_CR2_DMAR_MSK


#define USART_CR2_DMAT_POS		(7U)
#define USART_CR2_DMAT_MSK		0x1UL << USART_CR2_DMAT_POS
#define USART_CR2_DMAT			USART_CR2_DMAT_MSK

#define USART_CR2_RTSE_POS		(8U)
#define USART_CR2_RTSE_MSK		0x1UL << USART_CR2_RTSE_POS
#define USART_CR2_RTSE			USART_CR2_RTSE_MSK


#define USART_CR2_CTSE_POS		(9U)
#define USART_CR2_CTSE_MSK		0x1UL << USART_CR2_CTSE_POS
#define USART_CR2_CTSE			USART_CR2_CTSE_MSK

#define USART_CR2_CTSIE_POS		(10U)
#define USART_CR2_CTSIE_MSK		0x1UL << USART_CR2_CTSIE_POS
#define USART_CR2_CTSIE			USART_CR2_CTSIE_MSK

#define USART_CR2_ONEBIT_POS		(11U)
#define USART_CR2_ONEBIT_MSK		0x1UL << USART_CR2_ONEBIT_POS
#define USART_CR2_ONEBIT			USART_CR2_ONEBIT_MSK

#define USART_CR2_OVRDIS_POS		(12U)
#define USART_CR2_OVRDIS_MSK		0x1UL << USART_CR2_OVRDIS_POS
#define USART_CR2_OVRDIS			USART_CR2_OVRDIS_MSK

#define USART_CR2_DDRE_POS		(13U)
#define USART_CR2_DDRE_MSK		0x1UL << USART_CR2_DDRE_POS
#define USART_CR2_DDRE			USART_CR2_DDRE_MSK

#define USART_CR2_DEM_POS		(14U)
#define USART_CR2_DEM_MSK		0x1UL << USART_CR2_DEM_POS
#define USART_CR2_DEM			USART_CR2_DEM_MSK


#define USART_CR2_DEP_POS		(15U)
#define USART_CR2_DEP_MSK		0x1UL << USART_CR2_DEP_POS
#define USART_CR2_DEP			USART_CR2_DEP_MSK

#define USART_CR2_SCARCNT_POS		(17U)
#define USART_CR2_SCARCNT_MSK		0x1UL << USART_CR2_SCARCNT_POS
#define USART_CR2_SCARCNT			USART_CR2_SCARCNT_MSK
#define USART_CR2_SCARCNT_0			0x1UL << USART_CR2_SCARCNT_POS
#define USART_CR2_SCARCNT_1			0x2UL << USART_CR2_SCARCNT_POS
#define USART_CR2_SCARCNT_2			0x4UL << USART_CR2_SCARCNT_POS

#define USART_CR2_TXFTIE_POS		(23U)
#define USART_CR2_TXFTIE_MSK		0x1UL << USART_CR2_TXFTIE_POS
#define USART_CR2_TXFTIE			USART_CR2_TXFTIE_MSK

#define USART_CR2_TCBGTIE_POS		(24U)
#define USART_CR2_TCBGTIE_MSK		0x1UL << USART_CR2_TCBGTIE_POS
#define USART_CR2_TCBGTIE			USART_CR2_TCBGTIE_MSK

#define USART_CR2_RXFTCFG_POS		(25U)
#define USART_CR2_RXFTCFG_MSK		0x1UL << USART_CR2_RXFTCFG_POS
#define USART_CR2_RXFTCFG			USART_CR2_RXFTCFG_MSK
#define USART_CR2_RXFTCFG_0			0x1UL << USART_CR2_RXFTCFG_POS
#define USART_CR2_RXFTCFG_1			0x2UL << USART_CR2_RXFTCFG_POS
#define USART_CR2_RXFTCFG_2			0x4UL << USART_CR2_RXFTCFG_POS


#define USART_CR2_RXFTIE_POS		(28U)
#define USART_CR2_RXFTIE_MSK		0x1UL << USART_CR2_RXFTIE_POS
#define USART_CR2_RXFTIE			USART_CR2_RXFTIE_MSK


#define USART_CR2_RXFTIE_POS		(29U)
#define USART_CR2_RXFTIE_MSK		0x1UL << USART_CR2_RXFTIE_POS
#define USART_CR2_RXFTIE			USART_CR2_RXFTIE_MSK
#define USART_CR2_RXFTIE_0			0x1UL << USART_CR2_RXFTIE_POS
#define USART_CR2_RXFTIE_1			0x2UL << USART_CR2_RXFTIE_POS
#define USART_CR2_RXFTIE_2			0x4UL << USART_CR2_RXFTIE_POS


/*USART_BRR*/

#define USART_BRR_BRR_POS			(0U)
#define USART_BRR_BRR				((uint16_t)0xFFFF)

/*USART_GTPR*/

#define USART_GTPR_PSC_POS			(0U)
#define USART_GTPR_PSC_MSK			0xFFUL << USART_GTPR_PSC_POS
#define USART_GTPR_PSC				USART_CR2_PSC_MSK

#define USART_GTPR_GT_POS			(8U)
#define USART_GTPR_GT_MSK			0xFFUL << USART_GTPR_GT_POS
#define USART_GTPR_GT				USART_CR2_GT_MSK

/*USART_RTOR*/

#define USART_RTOR_RTO_POS			(0U)
#define USART_RTOR_RTO_MSK			0xFFFFFFUL << USART_RTOR_RTO_POS
#define USART_RTOR_RTO				USART_RTOR_RTO_MSK

#define USART_RTOR_BLEN_POS			(24U)
#define USART_RTOR_BLEN_MSK			0xFFUL << USART_RTOR_BLEN_POS
#define USART_RTOR_BLEN				USART_RTOR_BLEN_MSK

/*USART_RQR*/
#define USART_RQR_ABRRQ_POS			(0U)
#define USART_RQR_ABRRQ_MSK			0xFFUL << USART_RQR_ABRRQ_POS
#define USART_RQR_ABRRQ				USART_RQR_ABRRQ_MSK

#define USART_RQR_SBKRQ_POS			(1U)
#define USART_RQR_SBKRQ_MSK			0xFFUL << USART_RQR_SBKRQ_POS
#define USART_RQR_SBKRQ				USART_RQR_SBKRQ_MSK

#define USART_RQR_MMRQ_POS			(2U)
#define USART_RQR_MMRQ_MSK			0xFFUL << USART_RQR_MMRQ_POS
#define USART_RQR_MMRQ				USART_RQR_MMRQ_MSK

#define USART_RQR_RXFRQ_POS			(3U)
#define USART_RQR_RXFRQ_MSK			0xFFUL << USART_RQR_RXFRQ_POS
#define USART_RQR_RXFRQ				USART_RQR_RXFRQ_MSK

#define USART_RQR_TXFRQ_POS			(4U)
#define USART_RQR_TXFRQ_MSK			0xFFUL << USART_RQR_TXFRQ_POS
#define USART_RQR_TXFRQ				USART_RQR_TXFRQ_MSK

/*USART_ISR*/

#define USART_ISR_PE_POS			(0U)
#define USART_ISR_PE_MSK			0x1UL << USART_ISR_PE_POS
#define USART_ISR_PE				USART_ISR_PE_MSK



#define USART_ISR_FE_POS			(1U)
#define USART_ISR_FE_MSK			0x1UL << USART_ISR_FE_POS
#define USART_ISR_FE				USART_ISR_FE_MSK

#define USART_ISR_NE_POS			(2U)
#define USART_ISR_NE_MSK			0x1UL << USART_ISR_NE_POS
#define USART_ISR_NE				USART_ISR_NE_MSK

#define USART_ISR_ORE_POS			(3U)
#define USART_ISR_ORE_MSK			0x1UL << USART_ISR_ORE_POS
#define USART_ISR_ORE				USART_ISR_ORE_MSK

#define USART_ISR_IDLE_POS			(4U)
#define USART_ISR_IDLE_MSK			0x1UL << USART_ISR_IDLE_POS
#define USART_ISR_IDLE				USART_ISR_IDLE_MSK

#define USART_ISR_RXFNE_POS			(5U)
#define USART_ISR_RXFNE_MSK			0x1UL << USART_ISR_RXFNE_POS
#define USART_ISR_RXFNE				USART_ISR_RXFNE_MSK

#define USART_ISR_TC_POS			(6U)
#define USART_ISR_TC_MSK			0x1UL << USART_ISR_TC_POS
#define USART_ISR_TC				USART_ISR_TC_MSK

#define USART_ISR_TXFNF_POS			(7U)
#define USART_ISR_TXFNF_MSK			0x1UL << USART_ISR_TXFNF_POS
#define USART_ISR_TXFNF				USART_ISR_TXFNF_MSK

#define USART_ISR_LBDF_POS			(8U)
#define USART_ISR_LBDF_MSK			0x1UL << USART_ISR_LBDF_POS
#define USART_ISR_LBDF				USART_ISR_LBDF_MSK

#define USART_ISR_CTSIF_POS			(9U)
#define USART_ISR_CTSIF_MSK			0x1UL << USART_ISR_CTSIF_POS
#define USART_ISR_CTSIF				USART_ISR_CTSIF_MSK


#define USART_ISR_CTS_POS			(10U)
#define USART_ISR_CTS_MSK			0x1UL << USART_ISR_CTS_POS
#define USART_ISR_CTS				USART_ISR_CTS_MSK

#define USART_ISR_RTOF_POS			(11U)
#define USART_ISR_RTOF_MSK			0x1UL << USART_ISR_RTOF_POS
#define USART_ISR_RTOF				USART_ISR_RTOF_MSK

#define USART_ISR_EOBF_POS			(12U)
#define USART_ISR_EOBF_MSK			0x1UL << USART_ISR_EOBF_POS
#define USART_ISR_EOBF				USART_ISR_EOBF_MSK

#define USART_ISR_UDR_POS			(13U)
#define USART_ISR_UDR_MSK			0x1UL << USART_ISR_UDR_POS
#define USART_ISR_UDR				USART_ISR_UDR_MSK

#define USART_ISR_ABRE_POS			(14U)
#define USART_ISR_ABRE_MSK			0x1UL << USART_ISR_ABRE_POS
#define USART_ISR_ABRE				USART_ISR_ABRE_MSK

#define USART_ISR_ABRF_POS			(15U)
#define USART_ISR_ABRF_MSK			0x1UL << USART_ISR_ABRF_POS
#define USART_ISR_ABRF				USART_ISR_ABRF_MSK

#define USART_ISR_BUSY_POS			(16U)
#define USART_ISR_BUSY_MSK			0x1UL << USART_ISR_BUSY_POS
#define USART_ISR_BUSY				USART_ISR_BUSY_MSK

#define USART_ISR_CMF_POS			(17U)
#define USART_ISR_CMF_MSK			0x1UL << USART_ISR_CMF_POS
#define USART_ISR_CMF				USART_ISR_CMF_MSK



#endif /* BSP_USART_H_ */
