/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */



#include "main.h"
#include "BSP_GPIO.h"
#include "BSP_USART.h"

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif

//PB7

uint32_t address;

RCC_Typedef  *rcc  = RCC;
UART_Typedef *uart1 = USART1;
uint32_t num = 0;
uint32_t j=0;
uint32_t counter = 0;
uint16_t bitstatus = 0;
uint8_t GPIOInit (GPIO_TypeDef *gpiox);
uint8_t GPIOAInit (GPIO_TypeDef *gpiox);
uint8_t GPIOInitinput (GPIO_TypeDef *gpiox, uint32_t pinNumber, uint32_t speed, uint32_t pupdr);
uint8_t GPIOInitoutput (GPIO_TypeDef *gpiox, uint32_t pinNumber, uint32_t speed, uint32_t pupdr, uint32_t otyper);
uint8_t GPIOInitAF (GPIO_TypeDef *gpiox, uint32_t pinNumber, uint32_t speed, uint32_t pupdr, uint32_t afrl);

uint8_t GPIOSetpin(GPIO_TypeDef *gpiox, uint32_t pinNumber);
uint8_t GPIOResetpin(GPIO_TypeDef *gpiox, uint32_t pinNumber);
void delay(void);
int main(void)
{
ENABLE_GPIOA_CLOCK;
ENABLE_GPIOB_CLOCK;
ENABLE_GPIOC_CLOCK;
ENABLE_GPIOD_CLOCK;
ENABLE_GPIOE_CLOCK;
ENABLE_GPIOF_CLOCK;
ENABLE_GPIOG_CLOCK;
ENABLE_GPIOH_CLOCK;
ENABLE_GPIOI_CLOCK;

GPIOAInit (GPIOA);
GPIOInit (GPIOB);
GPIOInit (GPIOC);
GPIOInit (GPIOD);
GPIOInit (GPIOE);
GPIOInit (GPIOF);
GPIOInit (GPIOG);
GPIOInit (GPIOH);
GPIOInit (GPIOI);

GPIOInitoutput(GPIOB, 7, LOWSPEED, NOPULLUPPULLDOWN, OUTPUTPUSHPULL);
GPIOInitoutput(GPIOB, 2, LOWSPEED, NOPULLUPPULLDOWN, OUTPUTPUSHPULL);
GPIOInitoutput(GPIOC, 7, LOWSPEED, NOPULLUPPULLDOWN, OUTPUTPUSHPULL);
/*GPIOInitoutput(GPIOF, 8, LOWSPEED, NOPULLUPPULLDOWN, OUTPUTPUSHPULL);
//GPIOInit (GPIOC, 7, OUTPUTMODE, LOWSPEED);
GPIOInitinput(GPIOC, 13, LOWSPEED, NOPULLUPPULLDOWN);
*/
//GPIOInitoutput(GPIOA, 5, LOWSPEED, NOPULLUPPULLDOWN, OUTPUTPUSHPULL);

GPIOInitAF (GPIOA, 9, LOWSPEED, NOPULLUPPULLDOWN, AF7);
GPIOInitAF (GPIOA, 10, LOWSPEED, NOPULLUPPULLDOWN, AF7);

/*uart communication*/
// for transmition
/*enable USART1 clock*/
//CLEAR_REG(USART1->ISR);
ENABLE_USART1_CLOCK;
//1. program the word length USART_CR1
USART1->CR1 =(USART1->CR1) | 0U<<28;	//M1
USART1->CR1 =(USART1->CR1) | 0U<<12; //M0   //parity disable by default  //Oversampling is 16
//2. select the desired baud rate USART_BRR
USART1->BRR = 35;
//3. program the number of stop USART_CR2
USART1->CR2 = (USART1->CR2) | 0U<<12;
USART1->CR2 = (USART1->CR2) | 0U<<13;
//4. Enable the UE in USART_CR1
USART1->CR1 = (USART1->CR1) | 1U<<0;
//5. Enable TE bit in USART_CR1
USART1->CR1 = (USART1->CR1) | 1U<<3;
//6. write date to USART_TDR
uint8_t arr[1] = {25};
for (uint8_t i=0; i<20;i++)
{
USART1->TDR = (arr[0]);
delay();
}
//7. wait until TC flag is high
//while(USART1->ISR.7 != 0x1)
//{}


while(1)
{


		GPIOSetpin(GPIOB, 7);
		GPIOSetpin(GPIOC, 7);
		GPIOSetpin(GPIOF, 8);
		delay();
		GPIOResetpin(GPIOB, 7);
		GPIOResetpin(GPIOC, 7);
		GPIOResetpin(GPIOF, 8);


		  delay();

		  bitstatus = GPIOC->IDR;
		  if (bitstatus == 0x2000)
		  {
		  	counter++;
		  }






		  //for reception


}



return 0;
}







void delay(void)
{

	  for( j=0; j<10000; j++)
	  {
		  num = j;
		  __NOP();
	  }
	}



